### ISSUE TITLE
How to get user info after authorization success

### ISSUE THREAD

**Issue by dandisy** [grasses/codeigniter-oauth2-server#1]
This is a good job, 

but,
Please help me, How to get user info after authorization success

**Comment by grasses** [comment]
When user login third party app by `Authorization Code` grant type,
redirect to callback url whith code.
sdk do those steps:

1.use code get access_token
2.use state check callback safety
3.use access_token get user OpenId(unique open id)
4.use access_token + OpenId get user info

you can test here:

http://brentertainment.com/oauth2/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Fbrentertainment.com%2Foauth2%2Fclient%2Freceive_authcode&state=65b7bbc7d4fdfb385104f720b3149f9d
