### ISSUE TITLE
having trouble dealing with scopes

### ISSUE THREAD

**Issue by tomkidumbuyo** [grasses/codeigniter-oauth2-server#4]
i'd like to define my own scopes and automatically assign them to tokens based on their grant type so that 
a ) my users wont have to send a scope string while requesting for a token
b ) when i make changes to scopes, they are automatically added and deprecated from respective grant types.
I want to automatically add and remove scopes based on grant types only.

**Comment by grasses** [comment]
Scope is used to limit the authorization granted to the client by the resource owner.
a) Oauth server can change scopes, and if you don't want your users sanding scope, you need to write a SQL to find user scope in table `oauth_clients`
b) Also you can change scope by adding `$this->server->require_scope("scope name...");` before API users' request.

**Comment by grasses** [comment]
fixed #4
