### ISSUE TITLE
Multiple database connection

### ISSUE THREAD

**Issue by timyounes** [grasses/codeigniter-oauth2-server#5]
Hi,

It is possible to have multiple database connection in oauth2 codeigniter? I want to separate my authentication database from my protected resources.

**Comment by grasses** [comment]
Sorry, codeigniter-oauth2-server can not do it now.
But you can check user connections at api gateway.

**Comment by timyounes** [comment]
Thanks..
I already got a sulotion at it works because codeigniter has the ability to have multiple database and i apply that.. 😊..
Now my auth connection was separated from my protected resources.
