### ISSUE TITLE
Request and Response in XML format

### ISSUE THREAD

**Issue by timyounes** [grasses/codeigniter-oauth2-server#7]
Hi,

How to accept request in XML format and generate all response in XML format?

Thanks in advance

**Comment by grasses** [comment]
You can see oauth2 core project, this project is only an interface for oauth2 core project.

**Comment by timyounes** [comment]
what do you mean for that?

**Comment by grasses** [comment]
see oauth2 server for help: https://github.com/bshaffer/oauth2-server-php, this project is just interface example for oauth2-server-php

**Comment by timyounes** [comment]
Thanks @grasses 👍
